"""
Adaptive strategy selection and switching for Sudoku.

This module selects an initial solving strategy based on
measurable puzzle characteristics and selects alternative
strategies when the current strategy does not make sufficient
progress.
"""


CONSTRAINT_PROPAGATION = "constraint_propagation"
MRV_BACKTRACKING = "mrv_backtracking"
MIN_CONFLICTS = "min_conflicts"


def select_strategy(profile):
    """
    Select an initial Sudoku-solving strategy.

    Strategy selection uses measurable characteristics of the
    current Sudoku state.

    Policy:
    1. Use constraint propagation when many forced moves exist.
    2. Use Min-Conflicts only for very large and broadly
       unconstrained puzzles.
    3. Otherwise use MRV-based backtracking.

    Parameters
    ----------
    profile : dict
        Computational profile generated by the puzzle analyzer.

    Returns
    -------
    str
        Name of the selected solving strategy.
    """

    empty_cells = profile["empty_cells"]
    forced_moves = profile["forced_moves"]
    average_candidates = profile["average_candidates"]

    if empty_cells > 0:
        forced_move_ratio = (
            forced_moves / empty_cells
        )
    else:
        forced_move_ratio = 0.0

    # Strong propagation opportunity.
    if forced_move_ratio >= 0.30:
        return CONSTRAINT_PROPAGATION

    # Min-Conflicts is reserved for very large and broadly
    # unconstrained search spaces.
    #
    # The stricter threshold prevents the adaptive controller
    # from paying local-search overhead on ordinary puzzles.
    if (
        empty_cells >= 60
        and average_candidates >= 5.0
    ):
        return MIN_CONFLICTS

    # Default systematic search strategy.
    return MRV_BACKTRACKING


def switch_strategy(current_strategy, attempted_strategies):
    """
    Select the next strategy when the current strategy
    does not make sufficient progress.

    The switching order is:

    Constraint Propagation
        ↓
    MRV + Backtracking
        ↓
    Min-Conflicts

    A strategy that has already been attempted is skipped.

    Parameters
    ----------
    current_strategy : str
        Strategy that was most recently used.

    attempted_strategies : set
        Strategies that have already been attempted.

    Returns
    -------
    str or None
        The next unused strategy.

        Returns None when all available strategies
        have already been attempted.
    """

    strategy_order = [
        CONSTRAINT_PROPAGATION,
        MRV_BACKTRACKING,
        MIN_CONFLICTS,
    ]

    for strategy in strategy_order:

        if strategy == current_strategy:
            continue

        if strategy not in attempted_strategies:
            return strategy

    return None