"""
Adaptive strategy selection and switching for Sudoku.

This module selects an initial solving strategy based on
the computational characteristics of a Sudoku puzzle and
selects alternative strategies when the current strategy
does not make sufficient progress.
"""


CONSTRAINT_PROPAGATION = "constraint_propagation"
MRV_BACKTRACKING = "mrv_backtracking"
MIN_CONFLICTS = "min_conflicts"


def select_strategy(profile):
    """
    Select an initial Sudoku-solving strategy.

    Strategy selection is based on measurable characteristics
    of the current Sudoku state.

    Parameters
    ----------
    profile : dict
        Computational profile generated by the puzzle analyzer.

    Returns
    -------
    str
        Name of the selected solving strategy.
    """

    empty_cells = profile["empty_cells"]
    forced_moves = profile["forced_moves"]
    average_candidates = profile["average_candidates"]
    highly_constrained_cells = profile["highly_constrained_cells"]

    # Calculate the proportion of empty cells that currently
    # have exactly one possible value.
    if empty_cells > 0:
        forced_move_ratio = forced_moves / empty_cells
    else:
        forced_move_ratio = 0.0

    # Strong propagation opportunity.
    #
    # A relatively high proportion of forced moves indicates
    # that direct constraint propagation can make meaningful
    # progress without search.
    if forced_move_ratio >= 0.30:
        return CONSTRAINT_PROPAGATION

    # Highly constrained search space.
    #
    # A low average candidate count indicates that selecting
    # the most constrained variable is appropriate.
    if average_candidates <= 2.5:
        return MRV_BACKTRACKING

    # Large and relatively unconstrained search space.
    #
    # Local search becomes a candidate when many cells remain
    # and the average number of candidates is relatively high.
    if empty_cells >= 40 and average_candidates > 3.0:
        return MIN_CONFLICTS

    # If a substantial number of cells are highly constrained,
    # MRV is preferred for systematic search.
    if highly_constrained_cells >= 0.40 * empty_cells:
        return MRV_BACKTRACKING

    # Default to MRV-based backtracking because it provides
    # systematic and complete search.
    return MRV_BACKTRACKING


def switch_strategy(current_strategy, attempted_strategies):
    """
    Select the next strategy when the current strategy
    does not make sufficient progress.

    Parameters
    ----------
    current_strategy : str
        Strategy that was most recently used.

    attempted_strategies : set
        Strategies that have already been attempted.

    Returns
    -------
    str or None
        The next unused strategy.

        Returns None when all available strategies
        have already been attempted.
    """

    strategy_order = [
        CONSTRAINT_PROPAGATION,
        MRV_BACKTRACKING,
        MIN_CONFLICTS,
    ]

    for strategy in strategy_order:

        if strategy == current_strategy:
            continue

        if strategy not in attempted_strategies:
            return strategy

    return None