"""
Adaptive strategy selection for Sudoku.

This module selects an initial solving strategy based on
the computational characteristics of a Sudoku puzzle.
"""


CONSTRAINT_PROPAGATION = "constraint_propagation"
MRV_BACKTRACKING = "mrv_backtracking"
MIN_CONFLICTS = "min_conflicts"


def select_strategy(profile):
    """
    Select an initial Sudoku-solving strategy.

    Parameters
    ----------
    profile : dict
        Computational profile generated by the puzzle analyzer.

    Returns
    -------
    str
        Name of the selected solving strategy.
    """

    empty_cells = profile["empty_cells"]
    forced_moves = profile["forced_moves"]
    average_candidates = profile["average_candidates"]
    highly_constrained_cells = profile["highly_constrained_cells"]

    # If many cells have forced values, constraint propagation
    # is a suitable first strategy.
    if forced_moves > 0 or highly_constrained_cells > 0:
        return CONSTRAINT_PROPAGATION

    # If the puzzle has relatively few candidates per cell,
    # MRV-based backtracking is a suitable systematic strategy.
    if average_candidates <= 3.0:
        return MRV_BACKTRACKING

    # Larger and less constrained search spaces are candidates
    # for local-search exploration.
    if empty_cells >= 40 and average_candidates > 3.0:
        return MIN_CONFLICTS

    # Default to MRV-based backtracking when no stronger
    # characteristic determines the strategy.
    return MRV_BACKTRACKING